services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      # Optional: Set API key for basic authentication
      # QDRANT__SERVICE__API_KEY: your_api_key_here

      # Optional: Enable CORS for web dashboard access
      # QDRANT__SERVICE__HTTP_CORS__ENABLED: "true"

      # Optional: Log level configuration
      QDRANT__LOG_LEVEL: INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  qdrant-search:
    build:
      context: ..
      dockerfile: qdrant-search/Dockerfile
    ports:
      - "3009:3009"
    environment:
      - RUST_LOG=info
      - QDRANT_URL=http://qdrant:6334
      - QDRANT_API_KEY=${QDRANT_API_KEY:-}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-nomic-embed-text:latest}
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - SERVER_PORT=${SERVER_PORT:-3009}
    depends_on:
      - qdrant
    restart: unless-stopped

volumes:
  qdrant_storage:
    driver: local
