version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      # Optional: Set API key for basic authentication
      # QDRANT__SERVICE__API_KEY: your_api_key_here

      # Optional: Enable CORS for web dashboard access
      QDRANT__SERVICE__HTTP_CORS__ENABLED: "true"

      # Optional: Log level configuration
      QDRANT__LOG_LEVEL: INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  qdrant_storage:
    driver: local